const path = require('node:path')
const fs = require('node:fs')
const os = require('node:os')
const { Registry } = require('./registry.cjs')

function mkWs() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'canv-ws-'))
}

describe('Registry', () => {
  it('starts empty when no registry.json exists', () => {
    const r = new Registry(mkWs())
    expect(r.listEntries()).toEqual([])
    expect(r.get('foo')).toBe(null)
  })
  it('install creates registry entry with hash + version + null trust', () => {
    const ws = mkWs()
    const r = new Registry(ws)
    const e = r.install({ id: 'hello', version: '1.0.0' }, 'abc123')
    expect(e.id).toBe('hello')
    expect(e.manifestSha256).toBe('abc123')
    expect(e.version).toBe('1.0.0')
    expect(e.trustedAt).toBe(null)
    expect(e.enabled).toBe(false)
    const r2 = new Registry(ws)
    expect(r2.listEntries().map((x) => x.id)).toEqual(['hello'])
  })
  it('reinstall (same id, same hash) preserves trustedAt + enabled', () => {
    const ws = mkWs()
    const r = new Registry(ws)
    r.install({ id: 'x', version: '1.0.0' }, 'h1')
    r.setTrustedAt('x', '2026-05-17T00:00:00Z')
    r.setEnabled('x', true)
    const e = r.install({ id: 'x', version: '1.0.0' }, 'h1')
    expect(e.trustedAt).toBe('2026-05-17T00:00:00Z')
    expect(e.enabled).toBe(true)
  })
  it('reinstall with new hash forces re-trust', () => {
    const ws = mkWs()
    const r = new Registry(ws)
    r.install({ id: 'x', version: '1.0.0' }, 'h1')
    r.setTrustedAt('x', '2026-05-17T00:00:00Z')
    r.setEnabled('x', true)
    const e = r.install({ id: 'x', version: '1.0.1' }, 'h2')
    expect(e.trustedAt).toBe(null)
    expect(e.enabled).toBe(false)
    expect(e.version).toBe('1.0.1')
    expect(e.manifestSha256).toBe('h2')
  })
  it('uninstall removes the entry', () => {
    const ws = mkWs()
    const r = new Registry(ws)
    r.install({ id: 'x', version: '1.0.0' }, 'h1')
    r.uninstall('x')
    expect(r.get('x')).toBe(null)
  })
  it('setEnabled / setTrustedAt persist to disk', () => {
    const ws = mkWs()
    const r1 = new Registry(ws)
    r1.install({ id: 'x', version: '1.0.0' }, 'h1')
    r1.setTrustedAt('x', '2026-05-17T00:00:00Z')
    r1.setEnabled('x', true)
    const r2 = new Registry(ws)
    expect(r2.get('x').enabled).toBe(true)
    expect(r2.get('x').trustedAt).toBe('2026-05-17T00:00:00Z')
  })
  it('survives corrupted registry.json (returns empty)', () => {
    const ws = mkWs()
    fs.mkdirSync(path.join(ws, '.canv', 'extensions'), { recursive: true })
    fs.writeFileSync(path.join(ws, '.canv', 'extensions', 'registry.json'), 'not json')
    const r = new Registry(ws)
    expect(r.listEntries()).toEqual([])
  })
})
